# Generated by Django 3.2.9 on 2021-12-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hour_rate',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_full_time_employee',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='vacation_days',
            field=models.IntegerField(default=0),
        ),
    ]
