# Generated by Django 3.2.9 on 2021-12-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20211203_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_in_time',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_time',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_day_off',
            field=models.BooleanField(default=None),
        ),
    ]
