# Generated by Django 3.2.9 on 2021-12-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20211203_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
    ]
