# Generated by Django 3.2.9 on 2021-12-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20211203_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_out_time',
            field=models.TimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='is_day_off',
            field=models.BooleanField(default=False),
        ),
    ]
