# Generated by Django 3.2.9 on 2021-12-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_alter_attendance_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hour_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
